# Generated by Django 3.1.2 on 2021-09-12 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_555u', models.CharField(blank=True, max_length=20, null=True)),
                ('question_name', models.CharField(max_length=20)),
                ('question_delete', models.IntegerField()),
                ('question_category', models.IntegerField()),
                ('question_fe', models.CharField(max_length=20)),
                ('question_kk', models.CharField(blank=True, max_length=20, null=True)),
                ('question_558786u', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(default=123456, max_length=20)),
                ('user_uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('user_mobile', models.CharField(max_length=20, unique=True)),
                ('user_gender', models.CharField(choices=[(3, '保密'), (2, '女'), (1, '男')], max_length=2)),
                ('user_isDelete', models.IntegerField(default=0)),
                ('crete_time', models.DateTimeField(auto_now=True)),
                ('last_modify_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Base_user',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('choice_name', models.CharField(max_length=20)),
                ('choice_delete', models.IntegerField()),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('question_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
            options={
                'db_table': 'choice',
            },
        ),
    ]
