# Generated by Django 3.1.2 on 2021-09-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_558786u',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_fe',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[(1, '男'), (3, '保密'), (2, '女')], max_length=2),
        ),
    ]
