# Generated by Django 3.1.2 on 2021-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20210913_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[(1, '男'), (2, '女'), (3, '保密')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
