# Generated by Django 3.1.2 on 2021-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20210913_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_mobile',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
