# Generated by Django 3.1.2 on 2021-09-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20210913_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(5, '钻石卡会员'), (2, '银卡会员'), (4, '白金卡会员'), (3, '金卡会员'), (1, '普通用户')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[(2, '女'), (3, '保密'), (1, '男')], max_length=2),
        ),
    ]
