# Generated by Django 3.1.2 on 2021-09-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcase',
            table='TestCase',
        ),
    ]
